# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Thermal Comfort Study' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
  pod 'Toast-Swift', :git => "https://github.com/scalessec/Toast-Swift.git", :branch => 'master'
  
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'XCGLogger', '~> 4.0.0'
# Pods for Thermal Comfort Study

  target 'Thermal Comfort StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Thermal Comfort StudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
